basePath: /api/v1/
definitions:
  v1.response:
    properties:
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: REST API for Wish
  title: Wish API
  version: "1.0"
paths:
  /users/sign-up:
    post:
      consumes:
      - application/json
      description: create user account
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: User SignUp
      tags:
      - users-auth
securityDefinitions:
  StudentsAuth:
    in: header
    name: Authorization
    type: apiKey
  UsersAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
